thisdir = class/Microsoft.TeamFoundation
include ../../build/rules.make

LIBRARY = Microsoft.TeamFoundation.dll

LIB_MCS_FLAGS = /r:$(corlib) /r:System.dll /r:System.Xml.dll /r:System.Web.Services.dll
TEST_MCS_FLAGS =  $(LIB_MCS_FLAGS)

include ../../build/library.make

